/*********************************************
**********************************************
* Jenkinsfile for CI Multibranch Pipeline
* Project: AUTOSAR_SPIHandler_CI
* Brightskies ©
**********************************************
**********************************************/
pipeline {
    agent { label 'Master' }

    stages {
        stage('Identify Git Event') {
            steps {
                script {
                    if (env.ghprbPullId) { // Use ghprbPullId for PR number
                        echo "This is a pull request from branch: ${env.ghprbSourceBranch}"
                        currentBuild.displayName = "PR-${env.ghprbSourceBranch}-${env.ghprbPullId} - Build #${env.BUILD_NUMBER}"  
                    } else {
                        echo "Push Event detected for Build #${env.BUILD_NUMBER}"
                        currentBuild.displayName = "Push - Build #${env.BUILD_NUMBER}"
                    }
                }
            }
        }
        stage('Push Pipeline') {
            parallel {
                stage('SWE 4') {
                    stages {

                        /*******************************************************Build Stage***********************************************************/
                        stage('Build') {
                            steps {
                                script {
                                    if (env.BRANCH_NAME == 'Feature1') {
                                        /*Developer1*/

                                    } else if (env.BRANCH_NAME == 'Feature2') {
                                        /*Developer2*/

                                    } else if (env.BRANCH_NAME == 'Feature3') {
                                        /*Developer3*/


                                    }else if(env.BRANCH_NAME == 'main') {

                                        echo "============================================================================================="
                                        echo "Building source code..."
                                        echo "============================================================================================="
                                    }else{
                                        /*Nothing*/
                                    }
                                }
                            }
                        }
                        /************************************************ Static Code Analysis Stage*************************************************/
                        stage('Static Code Analysis') {
                            steps {
                                echo "Running Static Code Analysis..."
                                echo "============================================================================================="
                                script {
                                    if (env.BRANCH_NAME == 'Feature1') {
                                        /*Developer1*/  
                                        
                                    } else if (env.BRANCH_NAME == 'Feature2') {
                                        /*Developer2*/  
                                        
                                    } else if (env.BRANCH_NAME == 'Feature3') {
                                        /*Developer3*/  
                                        

                                    }else if(env.BRANCH_NAME == 'main') {
                                        echo "Running Static Code Analysis..."
                                        sh'''
                                        /var/jenkins_home/MisraC/Misra_src_check.sh STM_SPIHandler_Project/SPI/src/Spi.c
                                        '''

                                    }else{
                                        /*Nothing*/
                                    }
                                }
                                echo "============================================================================================="
                            }
                        }

                        /********************************************* Code Coverage Analysis Stage ****************************************************/
                        stage('Code Coverage Analysis ') {
                            steps {
                                echo "============================================================================================="
                                echo "Creating code coverage..."
                                sh '''
                                    cd 
                                    gcc -fprofile-arcs -ftest-coverage -o coverage main.c ../../STM_SPIHandler_Project/SPI/src/Spi.c
                                    // gcc -fprofile-arcs -ftest-coverage -o coverage main.c ../../STM_SPIHandler_Project/SPI/src/Spi.c
                                    ./coverage
                                    gcov -b -o . coverage-main.gcda
                                    gcov -b -o . coverage-Spi.gcda
                                    lcov --capture --directory . --output-file coverage.info
                                    genhtml coverage.info --output-directory out
                                '''
                                }
                                echo "============================================================================================="
                                echo "Generating code coverage report..."
                                echo "============================================================================================="
                            }
                        }
                        /*************************************************** Unit Testing Stage *******************************************************/
                        stage('Unit Testing ') {
                            steps {
                                echo "============================================================================================="
                                echo "Running unit tests with Google Test..."
                                echo "============================================================================================="

                                echo "============================================================================================="
                                echo "building the Gtest project"
                                dir('/UnitTesting/Gtest/') {
                                    sh 'cmake CMakeLists.txt'
                                    sh 'make'
                                    echo "============================================================================================="
                                        echo "Running unit tests with Google Test..."
                                    sh './Spi || true'
                                    echo "============================================================================================="

                                }
                            }
                        }
                        /******************************************************************************************************************************/   
                        stage('Allure Report SUT') {
                            steps {
                                echo "============================================================================================="
                                script {
                                    // if the test fails, the build will not fail
                                    def testResult = sh(script: './UnitTesting/Gtest/Spi --gtest_output=xml:report.xml', returnStatus: true)
                                    sh '''
                                    mkdir -p allure-results
                                    mv report.xml allure-results

                                    '''
                                    
                                    if (testResult != 0) {
                                        echo "Some tests failed. Check the Allure report for details."
                                    }
                                    sh 'allure generate allure-results --clean -o ALLURE_REPORT'
                                    // allure includeProperties: true, jdk: '', results: [[path: '/ALLURE_REPORT']]
                                }
                                echo "============================================================================================="
                            }
                        }
                    }
                }
            }
        }
        stage('Pull Request Pipeline') {
            parallel {
                stage('SWE 5') {
                    when {
                        expression { env.ghprbPullId } // Run only for pull request events
                    }
                    stages {
                        stage('Checkout PR') {
                            steps {
                                echo 'Checking out the PR branch...'
                                // Add your checkout or PR-specific steps here
                            }
                        }
                        stage('Integration Tests') {
                            steps {
                                echo 'Running Code Inspection tests...'
                                // Add your test steps here
                            }
                        }
                        
                    }
                }
            }
        }
        stage('Release Notes') {
            parallel {
                stage('Jira Release Notes') {
                    when {
                        expression { env.ghprbSourceBranch == 'master' && env.ghprbPullId }// Run only if the branch is 'master' and it's a pull request event
                    }
                    steps {
                            script {
                                echo "This is a pull request from branch: ${env.ghprbSourceBranch}"
                                currentBuild.displayName = "Release Notes v.${env.ghprbPullId} - Build #${env.BUILD_NUMBER}"  
                            }
                        echo "Generating Jira release notes..."
                        dir('/Tools/Jira') {
                            sh 'apt-get install jq -y'
                            sh 'chmod 777 ./jira.sh'
                            sh './jira.sh'
                            echo "============================================================================================="
                            echo "Jira Release Notes:"
                            sh 'cat jira_sprint_issues.txt'
                            echo "============================================================================================="
                        }
                    }
                } 
            }
        }
    }
}
